### ISSUE TITLE
ENHANCEMENT: Automatic robots.txt Generation

### ISSUE THREAD

**Issue by DavidVadnais** [theelectricbrain/Flastik#3]
## Feature Request: Automatic robots.txt Generation

**Description:**

From the todos:

It would be highly beneficial to have an automatic `robots.txt` generator built into Flastik. This feature would streamline the process of managing search engine crawling and indexing for generated websites.

**Use Case:**

Currently, users need to manually create and maintain their `robots.txt` file. This can be cumbersome, especially for larger sites or those with frequent content updates. An automatic generator would:

* Simplify the initial setup by providing sensible defaults.
* Allow for easy customization through configuration options within the generator's settings.
* Automatically reflect changes in site structure (e.g., new directories, updated content) in the `robots.txt`.
* Reduce the risk of errors associated with manual `robots.txt` creation.
* Improve SEO by ensuring correct crawling behavior.

**Proposed Functionality:**

The generator could offer the following features:

* **Basic Defaults:** Generate a standard `robots.txt` that allows crawling of all content by default, or disallows crawling of common temporary or development directories.
* **Configuration Options:**
    * Allow users to specify directories or files to disallow or allow.
    * Enable the inclusion of sitemap directives.
    * Support custom user-agents.
* **Integration with Site Structure:** Automatically update the `robots.txt` when the site structure changes (e.g., when new pages or directories are added).
* **Plugin/Extension capability:** Allow users to build plugins to extend the robots.txt generation.
* **Environment aware generation:** Allow for different robots.txt files depending on the build environment, example: development, staging, production.

**Example Configuration (Conceptual):**

```yaml
# Example configuration in Flastik config file
robots:
  disallow:
    - /temp/
    - /drafts/
  allow:
    - /public/images/
  sitemap: /sitemap.xml
  user-agent:
    googlebot:
      disallow: /private/
    *:
      allow: /
  crawl-delay:
    googlebot: 10
```
