### ISSUE TITLE
ENHANCEMENT: Automatic sitemap.xml Generation

### ISSUE THREAD

**Issue by DavidVadnais** [theelectricbrain/Flastik#4]
## Feature Request: Automatic sitemap.xml Generation for Flastik

**Description:**

From the todo's

the addition of an automatic `sitemap.xml` generator to Flastik. This feature would significantly improve SEO and simplify site management by automatically creating and updating a sitemap based on the generated site content.

**Use Case:**

Currently, Flastik users are required to manually create and maintain their `sitemap.xml` file. This is a time-consuming and error-prone process, especially for dynamic or frequently updated websites. An automatic generator would:

* Streamline the process of creating a sitemap, ensuring it accurately reflects the site's structure.
* Automatically update the sitemap whenever content is added, modified, or removed.
* Reduce the risk of outdated or inaccurate sitemaps, which can negatively impact SEO.
* Improve search engine crawlability and indexing.

**Proposed Functionality:**

The sitemap generator should offer the following features:

* **Automatic Generation:** Generate a `sitemap.xml` file based on the generated HTML files during the build process.
* **Configurable Inclusion/Exclusion:** Allow users to specify which pages or directories should be included or excluded from the sitemap.
* **Priority and Change Frequency:** Provide options to set the priority and change frequency for individual pages or groups of pages.
* **Integration with Flastik's Content Structure:** Automatically detect new pages and updates based on Flastik's content organization.
* **Customizable URL Generation:** Allow for custom URL generation based on Flastik's configuration (e.g., handling generated pagination, or other generated pages).
* **Sitemap Index Support:** If the site exceeds the 50,000 URL limit, automatically generate a sitemap index.
* **Plugin/Extension Capability:** Allow users to extend sitemap generation with plugins.
* **Environment aware generation:** Allow for different sitemaps depending on the build environment, example: development, staging, production.

**Example Configuration (Conceptual):**

```yaml
# Example configuration in Flastik's config file
sitemap:
  include:
    - /pages/
    - /posts/
  exclude:
    - /drafts/
    - /temp/
  priority:
    /posts/: 0.8
    /pages/: 0.5
  changefreq:
    /posts/: daily
    /pages/: weekly
```
